---
- hosts: localhost
  become: yes
  remote_user: ec2-user
  become_user: root
  tasks:
  - name: Download Long Term Jenkins release
    get_url:
      url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo

  - name: Import jenkins key from url
    ansible.builtin.rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

  - name: yum upgrade
    yum:
      name: '*'
      state: latest

  - name: Install Java
    shell: amazon-linux-extras install java-openjdk11 -y

  - name: Install Jenkins
    yum:
      name: jenkins
      state: latest

  - name: daemon-reload to pick up config changes
    ansible.builtin.systemd:
      daemon_reload: yes
    
  - name: Install Docker
    yum:
      name: docker
      state: latest

  - name: add user jenkins to docker group
    command: usermod -aG docker jenkins
  
  - name: add user ssm-user to docker group
    command: usermod -aG docker ssm-user
      
  - name: Starting and enabling required services
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items:
       - docker
       - jenkins
